/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'agro-green': {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        }
      }
    },
  },
  plugins: [],
  safelist: [
    'from-agro-green-50',
    'to-white',
    'bg-gradient-to-br',
    'bg-agro-green-50',
    'bg-agro-green-100',
    'bg-agro-green-200',
    'bg-agro-green-300',
    'bg-agro-green-400',
    'bg-agro-green-500',
    'bg-agro-green-600',
    'bg-agro-green-700',
    'bg-agro-green-800',
    'bg-agro-green-900',
    'text-agro-green-50',
    'text-agro-green-100',
    'text-agro-green-200',
    'text-agro-green-300',
    'text-agro-green-400',
    'text-agro-green-500',
    'text-agro-green-600',
    'text-agro-green-700',
    'text-agro-green-800',
    'text-agro-green-900',
    'border-agro-green-50',
    'border-agro-green-100',
    'border-agro-green-200',
    'border-agro-green-300',
    'border-agro-green-400',
    'border-agro-green-500',
    'border-agro-green-600',
    'border-agro-green-700',
    'border-agro-green-800',
    'border-agro-green-900',
    'ring-agro-green-500',
    'hover:bg-agro-green-50',
    'hover:bg-agro-green-100',
    'hover:bg-agro-green-200',
    'hover:bg-agro-green-300',
    'hover:bg-agro-green-400',
    'hover:bg-agro-green-500',
    'hover:bg-agro-green-600',
    'hover:bg-agro-green-700',
    'hover:bg-agro-green-800',
    'hover:bg-agro-green-900',
    'hover:text-agro-green-50',
    'hover:text-agro-green-100',
    'hover:text-agro-green-200',
    'hover:text-agro-green-300',
    'hover:text-agro-green-400',
    'hover:text-agro-green-500',
    'hover:text-agro-green-600',
    'hover:text-agro-green-700',
    'hover:text-agro-green-800',
    'hover:text-agro-green-900',
    'focus:ring-agro-green-500',
    'focus:border-agro-green-500'
  ]
} 